language: node_js

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn install
  - yarn lint

before_deploy:
  - yarn build --prefix-paths

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master